sudo: required

addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable

language: node_js
node_js:
  - "6"
before_script:
  - npm install -g gulp
script:
  - gulp lint
  - gulp all-non-e2e
  - npm stop